<template>
    <div class="loadingio-spinner-ellipsis-ot88exltivr">
        <div class="ldio-tfrrk3434dn">
            <div></div><div></div><div></div><div></div><div></div>
        </div>
    </div>
</template>

<style type="text/css">
@keyframes ldio-tfrrk3434dn {
    0% { transform: translate(12px,80px) scale(0); }
    25% { transform: translate(12px,80px) scale(0); }
    50% { transform: translate(12px,80px) scale(1); }
    75% { transform: translate(80px,80px) scale(1); }
    100% { transform: translate(148px,80px) scale(1); }
}
@keyframes ldio-tfrrk3434dn-r {
    0% { transform: translate(148px,80px) scale(1); }
    100% { transform: translate(148px,80px) scale(0); }
}
@keyframes ldio-tfrrk3434dn-c {
    0% { background: #6a6a6a }
    25% { background: #e2e2e2 }
    50% { background: #bdbdbd }
    75% { background: #979797 }
    100% { background: #6a6a6a }
}
.ldio-tfrrk3434dn div {
    position: absolute;
    width: 40px;
    height: 40px;
    border-radius: 50%;
    transform: translate(80px,80px) scale(1);
    background: #6a6a6a;
    animation: ldio-tfrrk3434dn 1s infinite cubic-bezier(0,0.5,0.5,1);
}
.ldio-tfrrk3434dn div:nth-child(1) {
    background: #979797;
    transform: translate(148px,80px) scale(1);
    animation: ldio-tfrrk3434dn-r 0.25s infinite cubic-bezier(0,0.5,0.5,1), ldio-tfrrk3434dn-c 1s infinite step-start;
}.ldio-tfrrk3434dn div:nth-child(2) {
    animation-delay: -0.25s;
    background: #6a6a6a;
}.ldio-tfrrk3434dn div:nth-child(3) {
    animation-delay: -0.5s;
    background: #979797;
}.ldio-tfrrk3434dn div:nth-child(4) {
    animation-delay: -0.75s;
    background: #bdbdbd;
}.ldio-tfrrk3434dn div:nth-child(5) {
    animation-delay: -1s;
    background: #e2e2e2;
}
.loadingio-spinner-ellipsis-ot88exltivr {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
    background: #ffffff;
}
.ldio-tfrrk3434dn {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
}
.ldio-tfrrk3434dn div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>